require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/guest_book_entries", type: :request do
  
  # GuestBookEntry. As you add validations to GuestBookEntry, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      GuestBookEntry.create! valid_attributes
      get guest_book_entries_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      guest_book_entry = GuestBookEntry.create! valid_attributes
      get guest_book_entry_url(guest_book_entry)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_guest_book_entry_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      guest_book_entry = GuestBookEntry.create! valid_attributes
      get edit_guest_book_entry_url(guest_book_entry)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new GuestBookEntry" do
        expect {
          post guest_book_entries_url, params: { guest_book_entry: valid_attributes }
        }.to change(GuestBookEntry, :count).by(1)
      end

      it "redirects to the created guest_book_entry" do
        post guest_book_entries_url, params: { guest_book_entry: valid_attributes }
        expect(response).to redirect_to(guest_book_entry_url(GuestBookEntry.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new GuestBookEntry" do
        expect {
          post guest_book_entries_url, params: { guest_book_entry: invalid_attributes }
        }.to change(GuestBookEntry, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post guest_book_entries_url, params: { guest_book_entry: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested guest_book_entry" do
        guest_book_entry = GuestBookEntry.create! valid_attributes
        patch guest_book_entry_url(guest_book_entry), params: { guest_book_entry: new_attributes }
        guest_book_entry.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the guest_book_entry" do
        guest_book_entry = GuestBookEntry.create! valid_attributes
        patch guest_book_entry_url(guest_book_entry), params: { guest_book_entry: new_attributes }
        guest_book_entry.reload
        expect(response).to redirect_to(guest_book_entry_url(guest_book_entry))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        guest_book_entry = GuestBookEntry.create! valid_attributes
        patch guest_book_entry_url(guest_book_entry), params: { guest_book_entry: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested guest_book_entry" do
      guest_book_entry = GuestBookEntry.create! valid_attributes
      expect {
        delete guest_book_entry_url(guest_book_entry)
      }.to change(GuestBookEntry, :count).by(-1)
    end

    it "redirects to the guest_book_entries list" do
      guest_book_entry = GuestBookEntry.create! valid_attributes
      delete guest_book_entry_url(guest_book_entry)
      expect(response).to redirect_to(guest_book_entries_url)
    end
  end
end
