---
development:
  cloud_name: hodsx14x9
  api_key: '631553237692739'
  api_secret: YRajnAn229aTxnmTypo9mV3UqpE
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: hodsx14x9
  api_key: '631553237692739'
  api_secret: YRajnAn229aTxnmTypo9mV3UqpE
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: hodsx14x9
  api_key: '631553237692739'
  api_secret: YRajnAn229aTxnmTypo9mV3UqpE
  enhance_image_tag: true
  static_file_support: false