default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: peterkoper_development
  username: gabrielwalsh
  password: amops

test:
  <<: *default
  database: peterkoper_test
  username: postgres
  password: amops

production:
  <<: *default
  database: <%= ENV['PETER_KOPER_DATABASE_DATABASE'] %>
  username: <%= ENV['PETER_KOPER_DATABASE_USERNAME'] %>
  password: <%= ENV['PETER_KOPER_DATABASE_PASSWORD'] %>